p1:
	./tinyasm.py p1.asm > p1.bin
	./tinyasm.py -p p1.asm > p1.txt
	cp p1.bin ../tinyarch/simulation/modelsim/

p2:
	./tinyasm.py p2.asm > p2.bin
	./tinyasm.py -p p2.asm > p2.txt
	cp p2.bin ../tinyarch/simulation/modelsim/

p3:
	./tinyasm.py p3.asm > p3.bin
	./tinyasm.py -p p3.asm > p3.txt
	cp p3.bin ../tinyarch/simulation/modelsim/
